import "@/globals.css";
import { SkeletonTheme } from "react-loading-skeleton";
import { Manrope, Poppins } from "next/font/google";

export const metadata = {
  title: "Inventory Management System",
  description: "Generated by create next app",
};

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-manrope",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

const RootLayout = async ({ children }) => {
  return (
    <SkeletonTheme baseColor="#d1e0e0" highlightColor="#edf7f6">
      <html lang="en" className={``}>
        <body
          className={`antialiased h-screen w-screen m-0 p-0 ${manrope.variable} ${poppins.variable}`}
        >
          <main className="h-full w-full font-primary">{children}</main>
        </body>
      </html>
    </SkeletonTheme>
  );
};

export default RootLayout;
